baseURL = 'https://www.postmortemsfromtheedge.com/'
languageCode = 'en-us'
title = 'Post Mortems from the Edge'
theme = "ananke"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[[params.ananke_socials]]
name = "mastodon"
url = "https://hachyderm.io/@elazaroh"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"