baseURL = 'http://www.postmortemsfromtheedge.com/'
languageCode = 'en-us'
title = 'Post Mortems from the Edge'
theme = "ananke"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

  